### ISSUE TITLE
can i batch upload diff files to different google drive accs?

### ISSUE THREAD

**Issue by heyeanne34** [jakbin/gdrive-bot#1]
Can i batch upload different files to different Google Drive accounts? Also, may I ask if there could be a tutorial or a way to reach you? I'm beginner in running github rep

**Comment by jakbin** [comment]
Yes , you just need access token for google drive that account.

**Comment by jakbin** [comment]
What do you mean with 'batch upload' ?

**Comment by jakbin** [comment]
@heyeanne34
